### ISSUE TITLE
"Rerun Failed Tests"  ignore @Stepwise annotation

### ISSUE THREAD

**Issue by katoquro** [cholick/idea-spock-enhancements#29]
If one of tests under @Stepwise annotated class fails "Rerun Failed Tests" will run all suite from failed test (not from the first one)

IntelliJ IDEA (Minerva) IU-144.3357.4
Build #IU-144.3357, built on January 26, 2016
JRE: 1.8.0_40-release-b127 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by cholick** [comment]
This isn't related to the plugin, this is an issue in IntelliJ itself. You'll want to raise it here: https://youtrack.jetbrains.com/issues/IDEA
