### ISSUE TITLE
Support for Mock() {...} no longer working in IntelliJ 2016.1

### ISSUE THREAD

**Issue by randomeizer** [cholick/idea-spock-enhancements#33]
After updating IntelliJ 2016.1 about a week ago, there is no longer any support for providing stubs/validators for methods inside a Mock() {...}

For example:

```
def value = Mock(Foo) {
    getBar() >> 1
}
```

Assuming that 'Foo.getBar()' is a valid method, it used to a) auto-suggest the methods and b) not display an underline under 'getBar()'. That is no longer the case.

Looking around, it seems there was a similar issue with IDEA 14, which was caused by the 'gdsl' being out of date. Not sure if that is the case here.

https://youtrack.jetbrains.com/issue/IDEA-135033

Let me know if I can be of assistance.

**Comment by cholick** [comment]
The issue is with IntelliJ itself, not this plugin. This plugin only adds a little syntax highlighting and some error checking. You should raise an issue in youtrack.jetbrains.com.

Toss a link to the issue you file and I'd be happy to +1 it.

**Comment by randomeizer** [comment]
Ah, ok, no worries. I've created the issue here: https://youtrack.jetbrains.com/issue/IDEA-156505
