### ISSUE TITLE
Highlight with Darcula theme

### ISSUE THREAD

**Issue by rubendm92** [cholick/idea-spock-enhancements#34]
I have just downloaded the plugin and it looks great, but I use the Darcula theme and the highlight for "given", "when" and so on it's a bit hard to read. Would it be possible to modify the color on Darcula theme? Thanks!

<img width="95" alt="screen shot 2016-06-12 at 19 57 44" src="https://cloud.githubusercontent.com/assets/4355136/15992906/09133c70-30d8-11e6-9571-f5f4a35ba9fd.png">

**Comment by cholick** [comment]
I've actually already added a preference that lets you pick the color:
Preferences -> Other Settings -> Spock -> Foreground
