### ISSUE TITLE
Invalid "extends" clause causes 100% CPU

### ISSUE THREAD

**Issue by eekboom** [cholick/idea-spock-enhancements#35]
This happens only with this plugin installed:

Type thjis in the editor
`class Foo extends Foo {`
and note that inspections never finish, IDEA eats 100% CPU without ever finishing.

This bit me when I tried to override a class from Spring boot: I intended to use class name completion after the second "Foo" to add the package name of the class with the same name from the spring library.

**Comment by cholick** [comment]
The bug is trigger not by an invalid `extends` clause, but by the class extending itself.

**Comment by eekboom** [comment]
Yes, sure that's what I meant: It is invalid to have an extends clause that names the current class.
While typing it was meant as a temporary state that should have become "class Foo extends org.springframework.Foo" by using class-name-completion.

Without the idea-spock-enhancements plugin IDEA just shows an error and happily continues.
With the plugin the inspector thread runs amok.

**Comment by cholick** [comment]
No need to close it, just adding a note with additional context since I had time to investigate, but not fix right now.

**Comment by eekboom** [comment]
Oops, the "close" was by mistake.
